"""The public sample reports at /examples.

This page exists to answer a question the product otherwise cannot: a free
result is a score with no angles and no coaching to argue with, so somebody
deciding whether to sign up has no idea what is behind the blur. Asking them to
create an account to find out is asking them to gamble.

So the thing worth testing is not that HTML comes back. It is that what comes
back is REAL: numbers from a fixture generated by running actual footage
through the actual pipeline, reference bands with their sources, and no
invented prose anywhere. A sample report that quietly became a mock-up would
still render perfectly.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.main import app
from app.services import examples

CONTENT = Path(__file__).resolve().parents[1] / "content" / "examples"
MEDIA = Path(__file__).resolve().parents[1] / "app" / "static" / "media" / "examples"


@pytest.fixture(scope="module")
def client():
    with TestClient(app) as c:
        yield c


@pytest.fixture(scope="module")
def samples():
    return examples.load_samples()


# --------------------------------------------------------------------------
# the fixtures are real
# --------------------------------------------------------------------------

def test_every_advertised_sample_exists(samples):
    assert {s.slug for s in samples} == set(examples.ORDER), (
        "a sample is advertised in ORDER but has no fixture -- regenerate with "
        "`python scripts/build_examples.py`"
    )


@pytest.mark.parametrize("slug", examples.ORDER)
def test_a_sample_records_which_clip_it_came_from(slug):
    """Provenance, so a number on a public page can always be traced back to
    the footage that produced it."""
    data = json.loads((CONTENT / f"{slug}.json").read_text(encoding="utf-8"))
    assert data.get("source_clip"), f"{slug} does not say which clip it is"
    assert data.get("title") and data.get("blurb")


@pytest.mark.parametrize("slug", examples.ORDER)
def test_a_sample_carries_a_measurement(slug):
    data = json.loads((CONTENT / f"{slug}.json").read_text(encoding="utf-8"))
    has_bands = bool(data.get("reference_bands") or data.get("angles_with_context"))
    assert has_bands, f"{slug} has no reference ranges to show"


def test_no_sample_carries_invented_coaching(samples):
    """The page is built from the deterministic half on purpose. LLM prose
    would be the only thing on it that is not a measurement, and it would be
    frozen text presented as though it were written for that clip."""
    for s in samples:
        assert "ai_recommendations" not in s.data
        assert "coach_report" not in s.data


def test_fixtures_stay_small_enough_to_review(samples):
    """These are committed. A fixture nobody can read in a diff is a fixture
    nobody checks."""
    for s in samples:
        size = (CONTENT / f"{s.slug}.json").stat().st_size
        assert size < 60_000, f"{s.slug}.json is {size // 1024} KB"


# --------------------------------------------------------------------------
# the pages
# --------------------------------------------------------------------------

def test_the_hub_lists_every_sample(client, samples):
    html = client.get("/examples").text
    for s in samples:
        assert f'href="/examples/{s.slug}"' in html
        assert s.title in html


@pytest.mark.parametrize("slug", examples.ORDER)
def test_each_sample_page_renders(client, slug):
    r = client.get(f"/examples/{slug}")
    assert r.status_code == 200
    assert "<h1" in r.text


def test_an_unknown_slug_lands_somewhere_useful(client):
    """404 for the crawler, the gallery for the human. A bare error page at
    the top of the funnel is a dead end."""
    r = client.get("/examples/not-a-sample")
    assert r.status_code == 404
    assert 'href="/examples/' in r.text


@pytest.mark.parametrize("slug", examples.ORDER)
def test_a_page_shows_measurements_against_their_bands(client, slug):
    """The table the product is actually for."""
    html = client.get(f"/examples/{slug}").text
    rows = re.findall(r'<tr class="(ok|near|out)">', html)
    assert len(rows) >= 4, f"{slug} renders only {len(rows)} band rows"


@pytest.mark.parametrize("slug", examples.ORDER)
def test_a_page_never_reports_a_clean_result_over_a_red_row(client, slug):
    """The page arguing with itself, which it did.

    A photo result has no ``detected_issues`` -- it puts a status on each
    angle instead -- and the findings section read only the video key. So
    run-photo printed "Nothing outside its range on this clip" directly under
    a table showing an ankle 7 degrees outside its band.
    """
    html = client.get(f"/examples/{slug}").text
    if '<tr class="out">' in html:
        assert "Nothing outside its range" not in html, (
            f"{slug} calls itself clean while rendering an out-of-range row"
        )


def test_a_photo_finding_names_the_angle_that_fired_it(client):
    html = client.get("/examples/run-photo").text
    findings = html.split("<h2>Findings</h2>", 1)[1].split("</section>", 1)[0]
    assert "Ankle Angle" in findings
    # And the 1-degree miss is reported as what it is, not as a fault: the
    # lede over the table promises exactly that tolerance.
    assert "Knee Angle" in findings
    assert "inside the method" in findings


def test_a_measured_but_unscored_angle_is_still_disclosed(client):
    """Both photo samples measure an angle the frame cannot grade. Dropping it
    silently would make the table look more complete than the analysis was."""
    for slug, angle in (("run-photo", "Hip Angle"), ("bike-aero", "Ankle Angle")):
        findings = (client.get(f"/examples/{slug}").text
                    .split("<h2>Findings</h2>", 1)[1].split("</section>", 1)[0])
        assert "not scored" in findings and angle in findings, slug


def test_a_page_names_the_source_of_at_least_one_band(client):
    """"Citations under the numbers" is the claim; this is the claim being
    true on the page a stranger sees."""
    html = client.get("/examples/bike-road").text
    assert "Retul" in html or "Bini" in html


def test_every_page_is_marked_as_a_sample(client):
    for slug in examples.ORDER:
        assert "Sample report" in client.get(f"/examples/{slug}").text


def test_every_page_carries_the_measurement_caveats(client):
    """The same honesty that is in the app has to survive onto the marketing
    page, or the page is selling a different product."""
    html = client.get("/examples/run-treadmill").text
    assert "near side" in html
    assert "not diagnoses" in html


def test_pages_are_cacheable(client):
    """Public, crawled, and unchanged between deploys."""
    r = client.get("/examples")
    assert "max-age" in r.headers.get("cache-control", "")


# --------------------------------------------------------------------------
# findable
# --------------------------------------------------------------------------

def test_the_sitemap_lists_the_samples(client):
    xml = client.get("/sitemap.xml").text
    assert "/examples</loc>" in xml
    for slug in examples.ORDER:
        assert f"/examples/{slug}</loc>" in xml


def test_the_landing_page_links_to_it(client):
    """The page exists to be seen before signup, so the pre-signup page has to
    point at it."""
    assert 'href="/examples"' in client.get("/").text


def test_the_app_links_to_it(client):
    assert 'href="/examples"' in client.get("/app").text


def test_the_pages_carry_seo_metadata(client):
    html = client.get("/examples/run-treadmill").text
    assert '<link rel="canonical"' in html
    assert 'property="og:title"' in html
    assert "<title>" in html


# --------------------------------------------------------------------------
# images
# --------------------------------------------------------------------------

def test_referenced_images_exist(samples):
    for s in samples:
        for url in (s.keyframe, s.kinogram):
            if not url:
                continue
            assert (MEDIA / Path(url).name).exists(), f"{url} is referenced and missing"


def test_images_are_light_enough_for_a_public_page(samples):
    """A 477 KB keyframe is fine inside a report somebody asked for and wrong
    on the page that has to load before they have decided to care."""
    for s in samples:
        for url in (s.keyframe, s.kinogram):
            if not url:
                continue
            path = MEDIA / Path(url).name
            size = path.stat().st_size
            assert size < 300_000, f"{path.name} is {size // 1024} KB"


def test_images_are_served(client, samples):
    url = next(s.keyframe for s in samples if s.keyframe)
    r = client.get(url)
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("image/")


def test_webp_is_served_as_an_image_everywhere(client):
    """Found here, true site-wide: `mimetypes` seeds from the host, the host
    did not know webp, and EVERY webp on the site -- landing page, capture
    guide, samples -- went out as application/octet-stream. That loses CDN
    image handling and can make a browser offer a download instead of a
    picture. The types are registered explicitly now rather than looked up."""
    for url in ("/media/film-fill-run.webp", "/media/examples/run-treadmill.webp"):
        r = client.get(url)
        assert r.status_code == 200, url
        assert r.headers["content-type"] == "image/webp", url


def test_the_media_types_are_declared_not_inherited():
    import mimetypes

    for ext, expected in ((".webp", "image/webp"), (".woff2", "font/woff2")):
        assert mimetypes.guess_type("x" + ext)[0] == expected
