"""Public sample reports: what a Flapp analysis actually looks like.

The conversion problem this exists for is written down elsewhere in this
codebase, in ``result_gating``: *a free result is a score with no angles and no
coaching to argue with*. Somebody deciding whether to sign up has no idea what
is behind the blur, and asking them to create an account to find out is asking
them to gamble. This page answers the question before the account.

It is built from FIXTURES generated by ``scripts/build_examples.py`` -- real
clips, run once through the real pipeline, trimmed and committed. Two reasons:
running MediaPipe on a crawler's request would be absurd, and more importantly
every number on this page is then a measurement of real footage rather than a
designer's placeholder. If a band moves or a scorer changes, the samples are
regenerated and the diff says what changed.

Deliberately NOT here: invented coaching prose. The samples carry the
deterministic half -- measurements, reference bands with their sources,
findings, the plan and the capture report -- which is the half that
distinguishes this product. A sample full of made-up coaching would be the one
thing on the page that is not real.

The page shell (SEO head, sidebar, footer, analytics) is imported from the
Academy renderer rather than copied. A second copy of that shell is how the
sidebar loses entries on one section and not another, which is a bug this
codebase has already fixed once.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.services.academy.renderer import SITE_NAME, _esc, _page

# backend/content/examples -- two levels up from app/services/, matching where
# the Academy keeps its own content.
CONTENT_DIR = Path(__file__).resolve().parents[2] / "content" / "examples"

# Display order on the hub. Video first: it is the product, and a photo sample
# leading would undersell what a clip buys.
ORDER = ("run-treadmill", "bike-road", "run-photo", "bike-aero")


@dataclass(frozen=True)
class Sample:
    slug: str
    title: str
    blurb: str
    mode: str
    sport: str
    data: dict[str, Any]

    # Video and photo results are different shapes, and the page should not
    # care: a video puts the score at the top level, a photo nests it under
    # ``score`` with a word for a grade ("Excellent") rather than a letter.
    @property
    def score(self) -> Any:
        if self.data.get("technique_score") is not None:
            return self.data["technique_score"]
        return (self.data.get("score") or {}).get("overall_score")

    @property
    def grade(self) -> Any:
        return (
            self.data.get("letter_grade")
            or (self.data.get("score") or {}).get("grade")
        )

    @property
    def keyframe(self) -> str | None:
        return self.data.get("keyframe_url")

    @property
    def kinogram(self) -> str | None:
        return self.data.get("kinogram_url")


@lru_cache(maxsize=1)
def load_samples() -> list[Sample]:
    """Every sample on disk, in display order. Cached for the process."""
    out: list[Sample] = []
    for slug in ORDER:
        path = CONTENT_DIR / f"{slug}.json"
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        out.append(Sample(
            slug=slug,
            title=data.get("title") or slug,
            blurb=data.get("blurb") or "",
            mode=data.get("mode") or "video",
            sport=data.get("sport_type") or data.get("sport") or "run",
            data=data,
        ))
    return out


def get_sample(slug: str) -> Sample | None:
    return next((s for s in load_samples() if s.slug == slug), None)


# ---------------------------------------------------------------------------
# pieces of a report
# ---------------------------------------------------------------------------

# How each measurement is named and what it is measured in. The bands the API
# publishes carry the numbers and the citation but no unit, and a value printed
# without one reads as unfinished on a page whose whole job is looking
# finished. Nothing here invents data -- it labels it.
_FIELD_META: dict[str, tuple[str, str]] = {
    "knee_at_bdc": ("Knee at the bottom of the stroke", "°"),
    "knee_at_tdc": ("Knee at the top of the stroke", "°"),
    "hip_angle_avg": ("Hip angle", "°"),
    "elbow_angle_avg": ("Elbow angle", "°"),
    "trunk_angle_avg": ("Trunk angle", "°"),
    "shoulder_angle_avg": ("Shoulder angle", "°"),
    "forearm_tilt_avg": ("Forearm tilt", "°"),
    "head_alignment_avg": ("Head alignment", ""),
    "pelvic_ratio": ("Pelvic tilt ratio", ""),
    "cadence_spm": ("Cadence", " spm"),
    "trunk_lean_avg": ("Trunk lean", "°"),
    "ground_contact_ms": ("Ground contact", " ms"),
    "flight_time_ms": ("Flight time", " ms"),
    "overstride_ratio": ("Overstride", " × leg length"),
    "vertical_oscillation_m": ("Vertical oscillation", " m"),
}


def _label_unit(field: str, band: dict[str, Any]) -> tuple[str, str]:
    label, unit = _FIELD_META.get(field, ("", ""))
    return (
        band.get("label") or label or field.replace("_", " ").capitalize(),
        band.get("unit") or unit,
    )


def _num(v: Any, digits: int = 1) -> str:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return "—"
    return f"{f:.{digits}f}".rstrip("0").rstrip(".") if digits else f"{f:.0f}"


def _score_block(s: Sample) -> str:
    """The headline, and -- the point of this page -- what it was built from."""
    withheld = s.data.get("score_withheld")
    cov = s.data.get("score_coverage") or {}
    if withheld:
        head = (
            '<div class="ex-score ex-score-none"><span class="n">Not scored</span>'
            f'<p class="why">{_esc(withheld.get("detail") or "")}</p></div>'
        )
    else:
        head = (
            f'<div class="ex-score"><span class="n">{_esc(str(s.score))}'
            '<small>/100</small></span>'
            f'<span class="g">{_esc(str(s.grade or "—"))}</span></div>'
        )
    cov_line = ""
    if cov.get("measures_total"):
        scored, total = cov.get("measures_scored"), cov.get("measures_total")
        weight = cov.get("weight_covered")
        detail = ""
        if cov.get("excluded"):
            reasons = "; ".join(
                f"{_esc(k.replace('_', ' '))} — {_esc(str(v))}"
                for k, v in (cov.get("excluded") or {}).items()
            )
            detail = f'<span class="ex-cov-why">Not graded: {reasons}</span>'
        elif cov.get("missing"):
            detail = (
                '<span class="ex-cov-why">Not measurable on this clip: '
                + _esc(", ".join(m.replace("_", " ") for m in cov["missing"]))
                + "</span>"
            )
        cov_line = (
            f'<p class="ex-cov">Scored on <b>{scored}</b> of <b>{total}</b> '
            f"measures — {round((weight or 0) * 100)}% of the rubric.{detail}</p>"
        )
    return head + cov_line


def _bands_table(s: Sample) -> str:
    """Measurements against their reference bands, with the source named.

    This is the table the product is actually for, and the citation is why a
    reader should believe the band rather than take our word for it.
    """
    summary = s.data.get("sport_specific_metrics") or {}
    angles = s.data.get("angles") or {}

    # A photo carries its ranges alongside each angle instead of in a separate
    # reference_bands block. Normalised here so the table is written once.
    bands = s.data.get("reference_bands") or {}
    if not bands:
        bands = {
            key: {
                "low": ctx.get("optimal_min"), "high": ctx.get("optimal_max"),
                "label": ctx.get("label"), "unit": "°",
                "source": "", "value": ctx.get("value"),
            }
            for key, ctx in (s.data.get("angles_with_context") or {}).items()
            if isinstance(ctx, dict)
        }

    rows = []
    for field, band in bands.items():
        if not isinstance(band, dict):
            continue
        # `lo`/`hi` is what reference_bands actually publishes; `low`/`high`
        # is the photo path's normalised form above.
        lo = band.get("lo", band.get("low"))
        hi = band.get("hi", band.get("high"))
        value = band.get("value")
        if value is None:
            value = summary.get(field)
        if value is None:
            value = angles.get(field)
        if value is None or lo is None or hi is None:
            continue
        try:
            v = float(value)
        except (TypeError, ValueError):
            continue
        inside = float(lo) <= v <= float(hi)
        label, unit = _label_unit(field, band)
        rows.append(
            f'<tr class="{"ok" if inside else "out"}">'
            f'<td class="m">{_esc(label)}</td>'
            f'<td class="v">{_num(v)}{_esc(unit)}</td>'
            f'<td class="b">{_num(lo)}–{_num(hi)}{_esc(unit)}</td>'
            f'<td class="s">{_esc(band.get("source") or "")}</td>'
            "</tr>"
        )
    if not rows:
        return ""
    return (
        '<section class="ex-sec"><h2>Measured against published ranges</h2>'
        '<p class="ex-lede">Every target names where it comes from. A value a '
        "degree or two outside a band is inside the method&rsquo;s own error, "
        "not a finding.</p>"
        '<div class="ex-tw"><table class="ex-bands">'
        "<thead><tr><th>Measurement</th><th>Yours</th><th>Reference</th>"
        "<th>Source</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div></section>"
    )


def _findings(s: Sample) -> str:
    issues = s.data.get("detected_issues") or []
    if not issues:
        return (
            '<section class="ex-sec"><h2>Findings</h2>'
            '<p class="ex-lede">Nothing outside its range on this clip.</p>'
            "</section>"
        )
    items = "".join(
        f'<li><b>{_esc(str(i.get("issue") or i.get("type") or "")).replace("_", " ")}'
        f'</b>{" — " + _esc(str(i.get("description") or i.get("message") or "")) if (i.get("description") or i.get("message")) else ""}</li>'
        for i in issues
    )
    return (
        f'<section class="ex-sec"><h2>Findings</h2><ul class="ex-list">{items}</ul>'
        "</section>"
    )


def _plan(s: Sample) -> str:
    """What to do next: bike adjustments, or running drills."""
    fit = (s.data.get("fit_plan") or {}).get("diagnostics") or []
    if fit:
        rows = "".join(
            f'<li><b>{_esc(str(d.get("component", "")).replace("_", " "))}</b>'
            f' — {_esc(str(d.get("reason") or ""))}</li>'
            for d in fit
        )
        return (
            '<section class="ex-sec"><h2>What to change on the bike</h2>'
            '<p class="ex-lede">In fitting order: each change moves the ones '
            "below it.</p>"
            f'<ol class="ex-list ex-num">{rows}</ol></section>'
        )
    plan = s.data.get("training_plan") or {}
    drills = plan.get("top_3_priorities") or []
    if not drills:
        return ""
    rows = "".join(
        f'<li><b>{_esc(str(d.get("drill") or d.get("title") or ""))}</b>'
        f'{" — " + _esc(str(d.get("cue") or d.get("why") or "")) if (d.get("cue") or d.get("why")) else ""}</li>'
        for d in drills
    )
    return (
        '<section class="ex-sec"><h2>What to work on</h2>'
        f'<ol class="ex-list ex-num">{rows}</ol></section>'
    )


def _capture(s: Sample) -> str:
    """How the recording itself limited the measurement -- the section nobody
    else in the category ships."""
    report = (s.data.get("sport_specific_metrics") or {}).get("capture_report") or {}
    checks = report.get("checks") or []
    if not checks:
        return ""
    rows = "".join(
        f'<tr class="c-{_esc(str(c.get("status")))}">'
        f'<td class="m">{_esc(str(c.get("label") or ""))}</td>'
        f'<td class="v">{_esc(str(c.get("measured") or ""))}</td>'
        f'<td class="b">{_esc(str(c.get("target") or ""))}</td></tr>'
        for c in checks
    )
    return (
        '<section class="ex-sec"><h2>What the recording cost the measurement</h2>'
        '<p class="ex-lede">Verdict: <b>'
        f'{_esc(str(report.get("verdict") or "—"))}</b>. Every analysis says how '
        "the clip limited it, and what to change next time.</p>"
        '<div class="ex-tw"><table class="ex-bands">'
        "<thead><tr><th>Check</th><th>Measured</th><th>Target</th></tr></thead>"
        f"<tbody>{rows}</tbody></table></div></section>"
    )


def _cta() -> str:
    return (
        '<section class="ex-cta"><h2>Film ten seconds and get your own</h2>'
        "<p>Side-on, phone upright, you filling the frame. Free account, no "
        "card.</p>"
        '<a class="ex-btn" href="/app">Analyze your form — free</a></section>'
    )


# ---------------------------------------------------------------------------
# pages
# ---------------------------------------------------------------------------

_CSS = """
.ex-hero{background:linear-gradient(135deg,#14294B 0%,#1D3E77 60%,#2F6DE0 100%);
  color:#fff;padding:44px 0 40px}
.ex-hero .wrap{max-width:1000px;margin:0 auto;padding:0 24px}
.ex-hero .eyebrow{font-family:var(--f-mono);font-size:11px;letter-spacing:.16em;
  text-transform:uppercase;color:rgba(255,255,255,.75);margin-bottom:12px}
.ex-hero h1{font-family:var(--f-display);font-weight:900;font-style:italic;
  text-transform:uppercase;font-size:clamp(30px,5vw,50px);line-height:1;margin:0 0 14px}
.ex-hero p{color:rgba(255,255,255,.88);max-width:62ch;font-size:17px;line-height:1.55;margin:0}
.ex-wrap{max-width:1000px;margin:0 auto;padding:36px 24px 72px}
.ex-grid{display:grid;gap:18px;grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}
.ex-card{display:block;background:#fff;border:1px solid var(--c-line);
  border-radius:var(--radius-lg);overflow:hidden;text-decoration:none;color:inherit;
  box-shadow:var(--shadow);transition:box-shadow .15s,transform .15s}
.ex-card:hover{box-shadow:var(--shadow-lg);transform:translateY(-2px)}
.ex-card img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;background:var(--c-media-bg)}
/* Block, not inline: this was a <span>, and padding on an inline box does not
   indent the lines that wrap -- the blurb ran into the card edge. */
.ex-card .body{display:block;padding:16px 18px 18px}
.ex-card .tag{font-family:var(--f-mono);font-size:10.5px;font-weight:600;
  letter-spacing:.1em;text-transform:uppercase;color:var(--c-blue)}
.ex-card h2{font-size:17px;color:var(--c-navy);margin:6px 0 6px;line-height:1.25}
.ex-card p{font-size:13.5px;color:var(--c-ink-soft);line-height:1.5;margin:0}
.ex-badge{display:inline-block;font-family:var(--f-mono);font-size:10.5px;
  font-weight:700;letter-spacing:.1em;text-transform:uppercase;padding:3px 9px;
  border-radius:4px;background:var(--c-panel-blue);color:var(--c-blue);margin-bottom:14px}
.ex-top{display:flex;gap:26px;flex-wrap:wrap;align-items:flex-start;margin-bottom:8px}
.ex-shot{flex:1 1 300px;min-width:260px}
.ex-shot img{width:100%;border-radius:var(--radius);background:var(--c-media-bg)}
.ex-side{flex:1 1 260px}
/* The grade is a letter on a video result ("B") and a word on a photo one
   ("Excellent"), so the badge cannot be a fixed-width circle beside the
   number: the word overflowed it and sat on top of "93/100". Stacked, and
   sized by its content -- min-width equal to the height keeps a single
   letter round, a word stretches the pill. */
.ex-score{display:flex;flex-direction:column;align-items:flex-start;gap:12px}
.ex-score .n{font-family:var(--f-mono);font-size:46px;font-weight:600;color:var(--c-navy);
  line-height:1;font-variant-numeric:tabular-nums}
.ex-score .n small{font-size:18px;color:var(--c-ink-soft)}
.ex-score .g{font-family:var(--f-display);font-style:italic;font-weight:900;
  font-size:26px;color:var(--c-blue);border:2.5px solid var(--c-blue);
  border-radius:999px;box-sizing:border-box;min-width:52px;height:52px;padding:0 18px;
  white-space:nowrap;display:inline-flex;align-items:center;justify-content:center}
.ex-score-none .n{font-family:var(--f-display);font-style:italic;font-size:30px;
  color:var(--c-warn);text-transform:uppercase}
.ex-score-none .why{font-size:13px;color:var(--c-ink-soft);margin:0;line-height:1.5;
  align-self:stretch}
.ex-cov{font-size:13.5px;color:var(--c-ink-soft);margin:14px 0 0;line-height:1.6;
  border-top:1px solid var(--c-line);padding-top:12px}
.ex-cov b{color:var(--c-navy);font-family:var(--f-mono)}
.ex-cov-why{display:block;font-size:12.5px;color:var(--c-ink-faint);margin-top:4px}
.ex-sec{margin-top:38px}
.ex-sec h2{font-family:var(--f-display);font-weight:800;font-size:22px;
  color:var(--c-navy);margin:0 0 8px}
.ex-lede{font-size:14.5px;color:var(--c-ink-soft);max-width:70ch;margin:0 0 14px;line-height:1.6}
.ex-tw{overflow-x:auto;border:1px solid var(--c-line);border-radius:var(--radius);background:#fff}
.ex-bands{border-collapse:collapse;width:100%;font-size:14px;min-width:520px}
.ex-bands th,.ex-bands td{padding:10px 14px;text-align:left;border-bottom:1px solid var(--c-line)}
.ex-bands thead th{font-family:var(--f-mono);font-size:10.5px;letter-spacing:.1em;
  text-transform:uppercase;color:var(--c-ink-faint);background:var(--c-panel)}
.ex-bands tbody tr:last-child td{border-bottom:none}
.ex-bands td.v,.ex-bands td.b{font-family:var(--f-mono);font-variant-numeric:tabular-nums;white-space:nowrap}
.ex-bands td.m{font-weight:600;color:var(--c-navy)}
.ex-bands td.s{font-size:12px;color:var(--c-ink-faint)}
.ex-bands tr.ok td.v{color:var(--st-good)}
.ex-bands tr.out td.v{color:var(--c-warn-text);font-weight:600}
.ex-bands tr.c-good td.m{color:var(--st-good)}
.ex-bands tr.c-warn td.m{color:var(--c-warn-text)}
.ex-bands tr.c-bad td.m{color:var(--st-bad)}
.ex-list{margin:0;padding-left:20px;font-size:14.5px;color:var(--c-ink-soft);line-height:1.65}
.ex-list li{margin:0 0 8px}
.ex-list b{color:var(--c-navy)}
.ex-kino{margin-top:38px}
.ex-kino img{width:100%;border-radius:var(--radius);background:var(--c-media-bg)}
.ex-cta{margin-top:48px;background:var(--c-panel-blue);border-radius:var(--radius-lg);
  padding:30px 28px;text-align:center}
.ex-cta h2{font-family:var(--f-display);font-weight:800;font-size:24px;color:var(--c-navy);margin:0 0 8px}
.ex-cta p{font-size:14.5px;color:var(--c-ink-soft);margin:0 0 18px}
.ex-btn{display:inline-block;background:var(--c-coral-btn);color:#fff;font-weight:700;
  padding:13px 26px;border-radius:var(--radius-btn);text-decoration:none;min-height:44px}
.ex-btn:hover{background:var(--c-coral-dk)}
.ex-back{display:inline-block;font-size:13.5px;color:var(--c-blue);margin-bottom:16px;text-decoration:none}
/* Full column width: the rule above it spans the page, and a 76ch measure
   under a full-width rule read as a broken paragraph rather than a note. */
.ex-note{font-size:12.5px;color:var(--c-ink-faint);line-height:1.6;margin-top:30px;
  border-top:1px solid var(--c-line);padding-top:14px}
@media(max-width:640px){.ex-wrap{padding:26px 18px 56px}.ex-score .n{font-size:38px}}
"""


def render_hub(base_url: str) -> str:
    samples = load_samples()
    cards = "".join(
        f'<a class="ex-card" href="/examples/{_esc(s.slug)}">'
        + (f'<img src="{_esc(s.keyframe)}" alt="{_esc(s.title)}" loading="lazy">'
           if s.keyframe else "")
        + '<div class="body">'
        f'<span class="tag">{_esc(s.sport)} · {_esc(s.mode)}</span>'
        f"<h2>{_esc(s.title)}</h2><p>{_esc(s.blurb)}</p>"
        "</div></a>"
        for s in samples
    )
    grid = (
        f'<div class="ex-grid">{cards}</div>' if cards
        else '<p class="ex-lede">Samples are being prepared.</p>'
    )
    body = (
        '<div class="ex-hero"><div class="wrap">'
        '<div class="eyebrow">Sample reports</div>'
        "<h1>See a real report<br>before you sign up</h1>"
        "<p>These are complete analyses of real footage — the same numbers, the "
        "same reference ranges and the same caveats you would get. Nothing here "
        "is a mock-up.</p>"
        "</div></div>"
        f'<main class="ex-wrap">{grid}'
        '<p class="ex-note">Each sample was produced by running the clip through '
        "the analyzer once and saving the result. Coaching notes are part of a "
        "real report and are left out here, because the rest of this page is "
        "measured and invented prose would be the only thing on it that "
        "isn&rsquo;t.</p>"
        f"{_cta()}</main>"
    )
    return _page(
        title=f"Sample reports — {SITE_NAME}",
        description="Complete Flapp analyses of real running and cycling "
                    "footage: joint angles against published reference ranges, "
                    "findings, and what to change.",
        canonical=f"{base_url}/examples",
        body=body,
        extra_css=_CSS,
        active="examples",
        jsonld={
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": f"{SITE_NAME} sample reports",
            "url": f"{base_url}/examples",
        },
    )


def render_sample(s: Sample, base_url: str) -> str:
    shot = (
        f'<div class="ex-shot"><img src="{_esc(s.keyframe)}" '
        f'alt="Annotated keyframe — {_esc(s.title)}"></div>'
        if s.keyframe else ""
    )
    # A run kinogram is five stride positions; a bike one is six points around
    # one pedal revolution. Same artifact, different thing being cut up.
    if s.kinogram and s.sport == "bike":
        kino_head, kino_lede = (
            "One pedal revolution",
            "Six positions either side of the top and bottom of the stroke, "
            "timed off the crank period rather than off frame counts.",
        )
    else:
        kino_head, kino_lede = (
            "One stride, five positions",
            "The ALTIS kinogram positions, found in the clip rather than posed "
            "— and published only when the analyzer trusts its own stride "
            "timing.",
        )
    kino = (
        f'<section class="ex-kino"><h2>{kino_head}</h2>'
        f'<p class="ex-lede">{kino_lede}</p>'
        f'<img src="{_esc(s.kinogram)}" alt="Kinogram — {_esc(s.title)}"></section>'
        if s.kinogram else ""
    )
    body = (
        f'<main class="ex-wrap">'
        '<a class="ex-back" href="/examples">&larr; All samples</a>'
        '<span class="ex-badge">Sample report</span>'
        f"<h1 style=\"font-family:var(--f-display);font-weight:900;font-style:italic;"
        f'text-transform:uppercase;font-size:clamp(26px,4vw,38px);color:var(--c-navy);'
        f'margin:0 0 10px;line-height:1.05">{_esc(s.title)}</h1>'
        f'<p class="ex-lede" style="font-size:16px">{_esc(s.blurb)}</p>'
        f'<div class="ex-top">{shot}'
        f'<div class="ex-side">{_score_block(s)}</div></div>'
        f"{_bands_table(s)}{_findings(s)}{_plan(s)}{kino}{_capture(s)}"
        '<p class="ex-note">Measured from a single side-on camera with 2D pose '
        "estimation. Only the near side of the body is measured; the far side is "
        "absent rather than assumed symmetrical. Reference ranges are efficiency "
        "targets from the literature, not diagnoses.</p>"
        f"{_cta()}</main>"
    )
    return _page(
        title=f"{s.title} — sample report · {SITE_NAME}",
        description=s.blurb,
        canonical=f"{base_url}/examples/{s.slug}",
        body=body,
        extra_css=_CSS,
        active="examples",
        og_type="article",
    )


def render_sitemap_entries(base_url: str) -> list[str]:
    """URLs for the site sitemap."""
    return [f"{base_url}/examples"] + [
        f"{base_url}/examples/{s.slug}" for s in load_samples()
    ]
